"""Regime detection thresholds."""

ADX_TREND_THRESHOLD = 25
ADX_RANGE_THRESHOLD = 20
VOL_CRISIS_THRESHOLD = 30
VOL_RANGE_THRESHOLD = 15
RET_TREND_THRESHOLD = 5

ADX_PERIOD = 14
VOL_WINDOW = 20
RET_WINDOW = 20
