"""Grid trading strategy constants."""

import os

from traders.common.config import LOG_DIR

CRYPTO_PAIRS = [
    "BTC/EUR", "ETH/EUR", "SOL/EUR", "AVAX/EUR", "LINK/EUR",
    "XRP/EUR", "DOGE/EUR", "SUI/EUR", "NEAR/EUR", "RENDER/EUR",
    "ADA/EUR", "DOT/EUR",
]

EXCHANGE_NAME = "kraken-grid"
PRICE_EXCHANGE = "kraken"

NUM_GRIDS = 10
RANGE_LOOKBACK_DAYS = 30
RANGE_MIN_PCT = 8.0
RANGE_MAX_PCT = 60.0
RANGE_BUFFER_PCT = 5.0

MAX_OPEN_GRIDS = 3
CAPITAL_PER_GRID_PCT = 0.33
MIN_TRADE_EUR = 5.0
GRID_HARD_STOP_PCT = -15.0

ROUND_TRIP_FEE_PCT = 0.52
MIN_GRID_SPREAD_PCT = 0.7

REBALANCE_INTERVAL_HOURS = 24
EXTEND_RANGE_PCT = 10.0

USE_REGIME_ROUTING = True

LOCK_FILE = os.path.join(LOG_DIR, "kraken_grid.lock")
COOLDOWN_MIN = 0
MAX_TRADES_PER_DAY = 100

LIMIT_ORDER_CYCLES = 2
