"""Momentum strategy constants."""

import os

from traders.common.config import LOG_DIR

CRYPTO_PAIRS = [
    "BTC/EUR", "ETH/EUR", "SOL/EUR", "AVAX/EUR", "LINK/EUR",
    "XRP/EUR", "DOGE/EUR", "SUI/EUR", "NEAR/EUR", "RENDER/EUR",
    "ADA/EUR", "DOT/EUR",
]

EXCHANGE_NAME = "kraken-momentum"
PRICE_EXCHANGE = "kraken"
LOCK_FILE = os.path.join(LOG_DIR, "kraken_momentum.lock")

ROUND_TRIP_FEE_PCT = 0.52
MAX_SPREAD_PCT = 0.40

DAILY_ENTRY_PCT = 2.0
HOURLY_ENTRY_PCT = 1.5
DAILY_WINDOW_MIN = 1440
ROT_DAILY_PCT = 2.5
ROT_HOURLY_PCT = 2.0

TTP_PEAK_PCT = 3.0
TTP_GIVEBACK_PCT = 1.0
PLOCK_PEAK_PCT = 5.0
PLOCK_FLOOR_PCT = 3.0
STOP_LOSS_PCT = -2.5
BREAKEVEN_PEAK_PCT = 2.0
STALE_FLAT_HOURS = 0.75
STALE_FLAT_PLPC = 1.0
STALE_MAX_HOURS = 1.5
MAX_HOLD_HOURS = 12.0

DEPLOY_FRACTION = 0.60
RISK_PER_TRADE_PCT = 4.0
MIN_TRADE_EUR = 0.45
MAX_OPEN_MOMENTUM = 2
MAX_TOTAL_OPEN = 5

COOLDOWN_MIN = 90
MAX_TRADES_PER_DAY = 4
DAILY_LOSS_BREAKER_PCT = -4.0
CONSULT_DEPLOY_FRACTION = 0.5
CONSULT_MIN_SCORE = 2.0

POOL_BASES = {p.split("/")[0] for p in CRYPTO_PAIRS}